services:
  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/app/indexer"]
    restart: always
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/app/api"]
    restart: always
    env_file:
      - .env
